pa_data_dir="./data/pao1_data"
# path to the data compendium file
data_compendium=$pa_data_dir"/all-pseudomonas-gene-normalized.pcl"
# path to the eADAGE models directory
models_dir=$pa_data_dir"/ensemble_models"
# path to the KEGG pathway file
pathway_file=$pa_data_dir"/pseudomonas_KEGG_terms.txt"

# specify the analysis output directory
analysis_dir=$pa_data_dir"/eADAGE_analysis"
mkdir -p $analysis_dir

# network output directory will contain (per model) the generated network file
# and, if applicable, 3 metadata files in a directory `metadata`:
#   - overrepresented pathways in each feature 
#   - pathway definitions for each feature after crosstalk removal
#   - positive and negative gene signature sets for each feature
network_output_dir=$analysis_dir"/network_construction"
#mkdir -p $network_output_dir

# count number of genes
N_genes=$(expr $(wc -l <$data_compendium) - 1)

# path to the list of genes we have data for in the compendium
pa_genes=$pa_data_dir"/pao1_compendium_genes.txt"
tail -n+2 $data_compendium | awk -F"\t" '{print $1}' > $pa_genes

# the model size that best supports the current P.a expression compendium k=300
N_features=300

# number of cores to use in parallel in run_pathcore_analysis.py,
# please modify this to accommodate your need.
N_cores=1

# if the gene's weight is +/- this number of standard deviations from the
# mean, we will include it in the +/- gene signatures of a feature
std_cutoff=2.5

# significance level used during both the pathway overrepresentation analysis
# and the edge permutation test
alpha=0.05

N_permutations=10000

permutation_output_dir=$analysis_dir"/permutation_test_n="$N_permutations

###############################################################################
# PathCORE analysis
###############################################################################

# Overrepresentation analysis and network construction:
# Generates the significant pathways files and metadata from the
# feature overrepresentation analysis on all models in $ensemble_directory.
#python3 build_co_occurrence_network.py \
#$models_dir $network_output_dir $pathway_file $N_genes \
#--n-features=$N_features --signature=eADAGE --signature-args=$std_cutoff \
#--alpha=$alpha --genes-list=$pa_genes --n-cores=$N_cores --shorten=PAO1_KEGG \
#--crosstalk-correction --all-genes --metadata

# Permutation test:
# Builds a network of pathway co-occurrence relationships and
# $N_permutations for each of the models. Evaluates each relationship
# (edge) against the null distribution generated by the permutations.
# Results in a single aggregate network where only edges considered
# significant under the permutation test remain.

python3 run_permutation_test.py \
$network_output_dir $permutation_output_dir \
--n-permutations=$N_permutations --n-features=$N_features \
--n-cores=2

###############################################################################
# PAO1 <> eADAGE <> KEGG web application DB setup
###############################################################################

filtered_network=$permutation_output_dir"/filtered_network.tsv"

# NOTE: this file must be edited after a user has set up an MLab account.
db_credentials_file="./data/pao1_web_info/eadage.yml"

python3 setup_pathcore_db.py \
$data_compendium $pathway_file $filtered_network $network_output_dir \
$db_credentials_file --models=10 --features=300 --is-pathcore-example

python3 cache_pathcore_edge_pages.py $filtered_network $db_credentials_file
