#!/bin/bash                                                                                                                                      
set -o errexit

# Kathleen Chen 2017 
# Large data files have been deposited into zenodo for versioning

##############################################################################
# eADAGE

# The normalized PAO1 gene expression compendium uses datasets
# from ArrayExpress.
# The script used to download and process the datasets into
# the compendium we provide in the zenodo record is available
# here: https://goo.gl/YjOEQl. 

# The 10 eADAGE models we use in the PathCORE eADAGE analysis
# were generated by running this script: https://goo.gl/MhGu3C.

# For more information about these data, please refer to 
# https://bitbucket.org/greenelab/eadage

# Citation:
# Tan J, Doing G, Lewis KA, Price CE, Chen KM, Cady KC, Perchuk B,
#     Laub MT, Hogan DA, Greene CS: System-wide automatic extraction
#     of functional signatures in Pseudomonas aeruginosa with eADAGE.
#     bioRxiv 2016, :078659.
##############################################################################
pa_data_dir="./pao1_data"

compendium_file=$pa_data_dir"/all-pseudomonas-gene-normalized.pcl"
compendium_url=https://zenodo.org/record/583694/files/all-pseudomonas-gene-normalized.pcl
# Download the zenodo .pcl file of the normalized P. aeruginosa
# expression compendium
curl -o $compendium_file $compendium_url

ensemble_models_dir=$pa_data_dir"/ensemble_models"
mkdir -p $ensemble_models_dir

# Download the zenodo tar.gz file of the 10 PAO1 eADAGE models
models_url=https://zenodo.org/record/583172/files/ensemble_models.tar.gz
curl $models_url | tar --extract --gzip --strip-components=1 --directory=$ensemble_models_dir

# The PAO1 KEGG pathway definitions file was generated by running the
# following command. Because these annotations continue to be updated,
# the `pseudomonas_KEGG_definitions.txt` file we used in our analysis is
# provided in $pa_data_dir to ensure reproducibility.
pseudomonas_KEGG_file=$pa_data_dir"/pseudomonas_KEGG_definitions.txt"

# Uncomment this command to get an up-to-date version:
# python ./get_annotations_from_Tribe.py $pseudomonas_KEGG_file KEGG

##############################################################################
# TCGA Pan-cancer dataset

# Citation:
# Way, G. (2016). Data used for training glioblastoma NF1 classifier
#     [Data set]. Zenodo. http://doi.org/10.5281/zenodo.56735
##############################################################################

tcga_data_dir="./tcga_data"

# Download the zenodo tar.gz file for the TCGA Pan-cancer NMF analysis
tcga_url=https://zenodo.org/record/56735/files/gbm_classifier_data.tar.gz
curl $tcga_url | tar --extract --gzip --strip-components=1 --directory=$tcga_data_dir

# We only need the HiSeqV2 (TCGA Pan-Cancer) dataset. Because this is the
# largest file in the tar.gz file, we did not create a separate zenodo record
# with only HiSeqV2; instead, we just remove the other 2 files after download.
rm $tcga_data_dir"/PANCAN_clinicalMatrix"
rm $tcga_data_dir"/PANCAN_mutation"

# Both the PAO1 and TCGA NMF models we used in our analysis are provided in
# this repository. Because Github limits file size to <50 Mb, the TCGA NMF
# model is provided as a .tar.gz and decompressed here.
tcga_NMF_model_dir=$tcga_data_dir"/NMF_model"
mkdir -p $tcga_NMF_model_dir

tcga_NMF_model_compressed=$tcga_data_dir"/NMF_300_features.tar.gz"
tar -xzvf $tcga_NMF_model_compressed -C $tcga_NMF_model_dir

# The PID pathway definitions file was generated by running the following
# command. For versioning, the original `c2.cp.v6.0.symbols.gmt` file we
# used in our analysis is provided in $tcga_data_dir. (See README for more
# information)

PID_file=$tcga_data_dir"/PID_pathway_definitions.txt"

# Uncomment this command to get the file from `c2.cp.v6.0.symbols.gmt`
# python get_PID_pathway_definitions.py ./tcga_data/c2.cp.v6.0.symbols.gmt $PID_file
